services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 6433:5432
    env_file:
      - compose.env
    volumes:
      - postgres_data_presupuestop:/var/lib/postgresql/data

volumes:
  postgres_data_presupuestop:
