name: brakeman
on: [pull_request]
jobs:
  brakeman:
    name: brakeman
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: brakeman
        uses: reviewdog/action-brakeman@v2
        with:
          reporter: github-pr-review
